version: "3"

services:

  chronograf:
    image: chronograf:1.4-alpine
    ports:
      - 8888:8888
    volumes:
      - chronograf:/var/lib/chronograf
    command: ["chronograf"]
    networks:
      influx_db_data:
        aliases:
          - chronograf

  kapacitor:
    image: kapacitor:1.4-alpine
    ports:
      - 9092:9092
    volumes:
      - kapacitor:/var/lib/kapacitor
      - ./conf/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    networks:
      influx_db_data:
        aliases:
          - kapacitor

networks:
  influx_db_data:
    external: true

volumes:
  kapacitor:
  chronograf:
  influxdb: