version: "3"

services:
  influxdb:
    image: influxdb:1.5-alpine
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:1.4-alpine
    ports:
      - 8888:8888
    links:
      - influxdb
    volumes:
      - chronograf:/var/lib/chronograf
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]

  kapacitor:
    image: kapacitor:1.4-alpine
    ports:
      - 9092:9092
    volumes:
      - kapacitor:/var/lib/kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

volumes:
  kapacitor:
  chronograf:
  influxdb: